name: Tests
on:
  push:
    branches: [ develop, master ]
  pull_request:
    branches: [ develop, master ]
jobs:
  tests:
    runs-on: 'Ubuntu-20.04'
    strategy:
      fail-fast: false
      matrix:
        php: ['7.4', '8.0']

    name: PHP ${{ matrix.php }}
    steps:
      -   uses: actions/checkout@v2
      -   uses: shivammathur/setup-php@v2
          with:
            php-version: '${{ matrix.php }}'
            coverage: none
            ini-values: 'memory_limit=-1'
      -   uses: "ramsey/composer-install@v1"
      -   name: Run Unit tests
          run: vendor/bin/phpunit